# Generated by Django 3.2.2 on 2021-05-08 16:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('RangoSup', models.IntegerField()),
                ('RangoInf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('idioma', models.CharField(blank=True, default='es', max_length=100, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('ideal_personal', models.TextField(blank=True, null=True)),
                ('reafirmar', models.TextField(blank=True, null=True)),
                ('liberar', models.TextField(blank=True, null=True)),
                ('adquirir', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.DateField()),
                ('proposito', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositos', to=settings.AUTH_USER_MODEL)),
                ('vinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propositos', to='core.vinculacion')),
            ],
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('cumplimiento', models.IntegerField()),
                ('proposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='core.proposito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
